import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import QueryProvider from './providers/QueryProvider'
import Header from '../shared/ui/Header'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
			>
				<QueryProvider>
					<div className='flex flex-col min-h-screen p-10 items-start'>
						<Header />
						<div className='w-full'>{children}</div>
					</div>
				</QueryProvider>
			</body>
		</html>
	)
}
